repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: check-yaml
        - id: check-json
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-added-large-files
        - id: check-merge-conflict
        - id: detect-private-key

    - repo: local
      hooks:
        - id: black
          files: luna
          name: black
          entry: black --config pyproject.toml
          types: [ python ]
          language: system

    - repo: local
      hooks:
        - id: isort
          name: isort
          entry: isort --settings-path pyproject.toml
          types: [ python ]
          language: system
